language: java
jdk:
  - oraclejdk8

service_name:
  - travis-pro

script:
  - mvn clean -U install

after_success:
  - mvn clean cobertura:cobertura coveralls:report -DrepoToken=Bss2ibmZGyQ2dPDEK21HALv67CMB8L5Bb